// <auto-generated />
using System;
using DietTracking.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DietTracking.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251227200657_Add19")]
    partial class Add19
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DietTracking.API.Models.Appointment", b =>
                {
                    b.Property<int>("AppointmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AppointmentId"));

                    b.Property<int?>("AppointmentStatusId")
                        .HasColumnType("integer");

                    b.Property<int?>("AppointmentTypeId")
                        .HasColumnType("integer");

                    b.Property<int?>("ClientId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.HasKey("AppointmentId");

                    b.HasIndex("AppointmentStatusId");

                    b.HasIndex("AppointmentTypeId");

                    b.HasIndex("ClientId");

                    b.ToTable("Appointments", "public");
                });

            modelBuilder.Entity("DietTracking.API.Models.AppointmentStatus", b =>
                {
                    b.Property<int>("AppointmentStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AppointmentStatusId"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.HasKey("AppointmentStatusId");

                    b.ToTable("AppointmentStatuses", "public");

                    b.HasData(
                        new
                        {
                            AppointmentStatusId = 1,
                            Description = "Waiting"
                        },
                        new
                        {
                            AppointmentStatusId = 2,
                            Description = "Approved"
                        },
                        new
                        {
                            AppointmentStatusId = 3,
                            Description = "Canceled"
                        },
                        new
                        {
                            AppointmentStatusId = 4,
                            Description = "Completed"
                        });
                });

            modelBuilder.Entity("DietTracking.API.Models.AppointmentType", b =>
                {
                    b.Property<int>("AppointmentTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AppointmentTypeId"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.HasKey("AppointmentTypeId");

                    b.ToTable("AppointmentTypes", "public");

                    b.HasData(
                        new
                        {
                            AppointmentTypeId = 1,
                            Description = "Online"
                        },
                        new
                        {
                            AppointmentTypeId = 2,
                            Description = "Phone"
                        },
                        new
                        {
                            AppointmentTypeId = 3,
                            Description = "F2F"
                        });
                });

            modelBuilder.Entity("DietTracking.API.Models.Client", b =>
                {
                    b.Property<int>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ClientId"));

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("ClientId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Clients", "public");
                });

            modelBuilder.Entity("DietTracking.API.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.ToTable("Users", "public");

                    b.HasData(
                        new
                        {
                            UserId = 99,
                            Email = "expert@diyet.com",
                            FirstName = "Örnek",
                            LastName = "Diyetisyen",
                            PasswordHash = "123",
                            Role = "Expert",
                            Username = "expert"
                        });
                });

            modelBuilder.Entity("DietTracking.API.Models.Appointment", b =>
                {
                    b.HasOne("DietTracking.API.Models.AppointmentStatus", "AppointmentStatus")
                        .WithMany("Appointments")
                        .HasForeignKey("AppointmentStatusId");

                    b.HasOne("DietTracking.API.Models.AppointmentType", "AppointmentType")
                        .WithMany("Appointments")
                        .HasForeignKey("AppointmentTypeId");

                    b.HasOne("DietTracking.API.Models.Client", "Client")
                        .WithMany("Appointments")
                        .HasForeignKey("ClientId");

                    b.Navigation("AppointmentStatus");

                    b.Navigation("AppointmentType");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("DietTracking.API.Models.Client", b =>
                {
                    b.HasOne("DietTracking.API.Models.User", "User")
                        .WithOne("Client")
                        .HasForeignKey("DietTracking.API.Models.Client", "UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DietTracking.API.Models.AppointmentStatus", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("DietTracking.API.Models.AppointmentType", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("DietTracking.API.Models.Client", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("DietTracking.API.Models.User", b =>
                {
                    b.Navigation("Client");
                });
#pragma warning restore 612, 618
        }
    }
}
